business_time:
  beginning_of_workday: 9:00 am
  end_of_workday: 6:00 pm
  holidays:
    - Jan 01, 2023
    - Setember 7th, 2022
    - November 15th, 2022
    - December 25th, 2022
  work_week:
    - mon 
    - tue
    - wed
    - thu
    - fri
